name: docs

on:
  push:
    paths:
      - 'docs/**'
    branches: [main]
  workflow_dispatch:

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create dist directory
      run: mkdir -p dist

    - name: Install Rust and build dependencies
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: 
    

    - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: docs
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
