name: docs

on:
  push:
    paths:
      - 'docs/**'
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    needs: deploy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create dist directory
      run: mkdir -p dist

    - name: Install Rust and build dependencies
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Check Rust code
      run: cargo check

    - name: Clean existing book
      run: rm -rf ./docs/book

    - name: Build Book
      run: mdbook build docs

    - name: Verify generated book
      run: mdbook test docs

    - name: Move Book to Dist
      run: mv ./docs/book ./dist

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: dist
