name: docs

on:
  push:
    paths:
      - 'docs/**' # 监视docs目录及其所有子目录中的文件变化
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
        with:
          fetch-depth: 0

    - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Setup mdbook
        run: cargo install mdbook

      - name: Build Book and Move
        run: mdbook build docs && mv ./docs/book ./dist

